name: Basic-Schulung 
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: My first Action
    runs-on: Unbuntu-latest
    steps: 
      - uses: actions/checkout@v1  
      - uses: ./action-a
        with:
          MY_NAME: Oliver
